version: '3'

services:

  vtigercrm:
    image: dotriver/vtigercrm
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - VTIGER_DB_NAME=vtigercrm
      - VTIGER_DB_USERNAME=vtigercrm
      - VTIGER_DB_PASSWORD=password
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - ADMIN_EMAIL=admin@exemple.org
    ports:
      - 8080:80
    networks:
      default:
    volumes:
      - vtigercrm-data:/var/www/vtigercrm/
    

  mariadb:
    image: dotriver/mariadb
    environment:
      - ROOT_PASSWORD=password
      - DB_0_NAME=vtigercrm
      - DB_0_PASS=password
    ports:
      - 3306:3306
      - 8081:80
    volumes:
      - mariadb-data:/var/lib/mysql/
      - mariadb-config:/etc/mysql/
    networks:
      default:
    
volumes:
    mariadb-data:
    mariadb-config:
    vtigercrm-data:
